MovieSearch/MovieSearch/ViewModels/Movies/MovieDetailsViewModel.cs
using MovieSearch.Models;
using System.Collections.Generic;

namespace MovieSearch.ViewModels.Movies
{
    public class MovieDetailsViewModel
    {
        public Movie Movie { get; set; }

        public MovieMark Mark { get; set; }

        public IEnumerable<Review> Reviews { get; set; }

        public string IsFavourite { get; set; }

        public int ProfileId { get; set; }

    }
}

MovieSearch/MovieSearch/ViewModels/Movies/MovieEditViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using MovieSearch.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieSearch.ViewModels.Movies
{
    public class MovieEditViewModel
    {
        public Movie Movie { get; set; }

        public SelectList Genres { get; set; }
    }
}

MovieSearch/MovieSearch/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using MovieSearch.Data;
using MovieSearch.Models;
using MovieSearch.ViewModels.Movies;
using MovieSearch.RenderHelper;
using Microsoft.Extensions.Localization;

namespace MovieSearch.Controllers
{
    public class MoviesController : Controller
    {
        private readonly ApplicationDbContext _context;

        private readonly ILogger<MoviesController> _logger;

        private readonly UserManager<ApplicationUser> _userManager;

        private readonly IStringLocalizer<MoviesController> _localizer;

        public MoviesController(
            ILogger<MoviesController> logger,
            ApplicationDbContext context,
            UserManager<ApplicationUser> userManager,
            IStringLocalizer<MoviesController> localizer)
        {
            _logger = logger;
            _context = context;
            _userManager = userManager;
            _localizer = localizer;
        }

        // GET: Movies
        public async Task<IActionResult> Index()
        {
            IQueryable<Movie> movies;
            var viewModel = new MovieIndexViewModel();

            movies = _context.Movies.Include(m => m.Genre);
            viewModel.Genres = new SelectList(_context.MovieGenres, "Id", "Name");


            viewModel.Movies = await movies.ToListAsync();

            return View(viewModel);
        }


        [NoDirectAccess]
        public async Task<IActionResult> IndexSort(int genreId = 0)
        {
            IQueryable<Movie> movies;
            var viewModel = new MovieIndexViewModel();

            if (genreId > 0)
            {
                movies = _context.Movies.Include(m => m.Genre).Where(m => m.GenreId == genreId);

                //var genre = await _context.MovieGenres.FindAsync(genreId);
                viewModel.Genres = new SelectList(_context.MovieGenres, "Id", "Name", genreId);

            }
            else
            {
                movies = _context.Movies.Include(m => m.Genre);
                viewModel.Genres = new SelectList(_context.MovieGenres, "Id", "Name");
            }

            viewModel.Movies = await movies.ToListAsync();

            return PartialView("_ViewAll", viewModel);
        }

        [NoDirectAccess]
        public async Task<IActionResult> IndexSearch(string searchValue)
        {
            IQueryable<Movie> movies = _context.Movies.Include(m => m.Genre);
            var viewModel = new MovieIndexViewModel();

            if (!string.IsNullOrEmpty(searchValue))
            {
                movies = movies.Where(m => m.Name.Contains(searchValue));
            }


            ViewData["SearchValue"] = searchValue;
            viewModel.Genres = new SelectList(_context.MovieGenres, "Id", "Name");
            viewModel.Movies = await movies.ToListAsync();

            return PartialView("_ViewAll", viewModel);
        }

        // GET: Movies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFoundWithLogger(nameof(id));
            }

            var movie = await _context.Movies
                .Include(m => m.Genre)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (movie == null)
            {
                return NotFoundWithLogger(nameof(movie));
            }

            var userId = _userManager.GetUserId(User);


            var viewModel = new MovieDetailsViewModel { Movie = movie };
            viewModel.Reviews = _context.Reviews
                .AsNoTracking()
                .Include(r => r.UserProfile)
                .ThenInclude(p => p.User)
                .ThenInclude(u => u.ProfilePicture)
                .Where(r => r.MovieId == id);

            if (userId != null)
            {
                var profileId = (await _context.MoviesProfiles.FirstOrDefaultAsync(p => p.UserId == userId)).Id;
                viewModel.ProfileId = profileId;

                var mark = await _context.MovieMarks
                    .AsNoTracking()
                    .FirstOrDefaultAsync(m =>
                    m.Movie.Id == movie.Id && m.UserProfile.UserId == userId);

                bool isFavourite = IsFavouriteMovie(userId, movie.Id);

                viewModel.Mark = mark;
                if (isFavourite) viewModel.IsFavourite = _localizer["In Favourites"];
                else viewModel.IsFavourite = _localizer["Add Favourite"];
            }

            return View(viewModel);
        }

        private bool IsFavouriteMovie(string userId, int movidId)
        {
            var favMovie = _context.FavouriteMovies
               .Include(f => f.UserProfiles)
               .ThenInclude(f => f.Profile)
               .FirstOrDefault(f => f.MovieId == movidId);

            return favMovie.UserProfiles.Any(f => f.Profile.UserId == userId);
        }

        // GET: Movies/Create
        // Only admin can create new a db record. 
        [Authorize(Roles = "SuperAdmin")]
        public IActionResult Create()
        {
            MovieEditViewModel viewModel = new MovieEditViewModel
            {
                Genres = new SelectList(_context.MovieGenres, "Id", "Name"),
            };

            return View(viewModel);
        }

        // POST: Movies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "SuperAdmin")]
        public async Task<IActionResult> Create([Bind("Id,Name,Image,Title,Year,Country,GenreId")] Movie movie)
        {
            if (ModelState.IsValid)
            {
                _context.AddRange(movie, new FavouriteMovie { Movie = movie });
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            var genre = await _context.MovieGenres.FindAsync(movie.GenreId);
            MovieEditViewModel viewModel = new MovieEditViewModel
            {
                Movie = movie,
                Genres = new SelectList(_context.MovieGenres, "Id", "Name", genre.Name),
            };

            return View(viewModel);
        }

        // GET: Movies/Edit/5
        [Authorize(Roles = "SuperAdmin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFoundWithLogger(nameof(id));
            }

            var movie = await _context.Movies.Include(m => m.Genre).FirstOrDefaultAsync(m => m.Id == id);
            if (movie == null)
            {
                return NotFoundWithLogger(nameof(movie));
            }

            MovieEditViewModel viewModel = new MovieEditViewModel
            {
                Movie = movie,
                Genres = new SelectList(_context.MovieGenres, "Id", "Name"),
            };

            return View(viewModel);
        }

        // POST: Movies/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "SuperAdmin")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Image,Title,Year,Country,OveralRating,GenreId")] Movie movie)
        {
            if (id != movie.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(movie);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MovieExists(movie.Id))
                    {
                        return NotFoundWithLogger(nameof(movie));
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            MovieEditViewModel viewModel = new MovieEditViewModel
            {
                Movie = movie,
            };

            var genre = await _context.MovieGenres.FindAsync(movie.GenreId);
            viewModel.Genres = new SelectList(_context.MovieGenres, "Id", "Name", genre.Name);
            return View(viewModel);
        }

        // GET: Movies/Delete/5
        [Authorize(Roles = "SuperAdmin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                //_logger.LogError("Movie with id {0} not found in the database", id);
                //return NotFound();
                return NotFoundWithLogger(nameof(id));
            }

            var movie = await _context.Movies
                .Include(m => m.Genre)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (movie == null)
            {
                //_logger.LogError("Movie with id {0} not found in the database", id);
                //return NotFound();
                return NotFoundWithLogger(nameof(movie));
            }

            return View(movie);
        }

        // POST: Movies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "SuperAdmin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var movie = await _context.Movies.FindAsync(id);
            _context.Movies.Remove(movie);

MovieSearch/MovieSearch/Controllers/UserMoviesController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion.Internal;
using Microsoft.Extensions.Localization;
using Microsoft.Extensions.Logging;
using MovieSearch.Data;
using MovieSearch.Models;
using MovieSearch.ViewModels.UserMovies;

namespace MovieSearch.Controllers
{
    [Authorize]
    public class UserMoviesController : Controller
    {

        public class MovieComparer : IEqualityComparer<Movie>
        {
            public bool Equals([AllowNull] Movie x, [AllowNull] Movie y)
            {
                if (y == null || x == null)
                {
                    return false;
                }

                // TODO: write your implementation of Equals() here
                return x.Id == y.Id;
            }

            public int GetHashCode([DisallowNull] Movie obj)
            {
                return base.GetHashCode();
            }
        }

        private readonly ApplicationDbContext _context;
        private readonly IStringLocalizer<UserMoviesController> _localizer;
        private readonly ILogger<UserMoviesController> _logger;
        private readonly UserManager<ApplicationUser> _userManager;

        public UserMoviesController(
            ILogger<UserMoviesController> logger,
            ApplicationDbContext context,
            UserManager<ApplicationUser> userManager,
            IStringLocalizer<UserMoviesController> localizer)
        {
            _logger = logger;
            _context = context;
            _localizer = localizer;
            _userManager = userManager;
        }

        [Route("ViewedMovies/{userId:Guid}/[Action]", Name = "Favourites")]
        public async Task<IActionResult> Favourites(string userId)
        {
            var currentUserId = _userManager.GetUserId(User);

            var userProfile = await _context.MoviesProfiles
                .Include(u => u.User)
                .Include(p => p.FavouriteMovies)
                .ThenInclude(f => f.Movie)
                .ThenInclude(f => f.Movie)
                .ThenInclude(m => m.Genre)
                .Include(p => p.Marks)
                .ThenInclude(m => m.Movie)
                .FirstOrDefaultAsync(p => p.UserId == userId);

            if(userProfile == null)
            {
                return NotFound();
            }

            // Double select 'cause FavouriteMovie has Movie;
            var favourites = userProfile.FavouriteMovies
                .Select(f => f.Movie)
                .Select(f => f.Movie)
                .OrderBy(f => f.Name);

            var marks = userProfile.Marks.OrderBy(m => m.Movie.Name);

            var favouritesMarks = marks
                .Where((m) => { return favourites.Any(mv => mv.Id == m.MovieId); })
                .OrderBy(m => m.Movie.Name);

            var markedFavourites = favouritesMarks.Select(m => m.Movie);

            var unmarkedFavourites = favourites.Except(markedFavourites, new MovieComparer());

            var moviesAndMarks = markedFavourites.Zip(favouritesMarks).ToList();

            foreach (var movie in unmarkedFavourites)
            {
                moviesAndMarks.Add((movie, null));
            }

            moviesAndMarks = moviesAndMarks.OrderBy(m => m.First.Name).ToList();

            var viewModel = new UserMoviesViewModel
            {
                MoviesAndMarks = moviesAndMarks,

                ForCurrentUser = userId == currentUserId,

                UserName = userProfile.User.UserName,

                ReturnUrl = Url.RouteUrl("Favourites", new { UserId = userId }) //"/UserMovies/"
            };

            return View(viewModel);
        }

        [Route("ViewedMovies/{userId:Guid}/[Action]", Name = "Viewed")]
        public async Task<IActionResult> ViewedMovies(string userId)
        {
            var currentUserId = _userManager.GetUserId(User);
            var userProfile = await _context.MoviesProfiles
                .Include(p => p.User)
                .Include(p => p.Marks)
                .ThenInclude(m => m.Movie)
                .FirstOrDefaultAsync(p => p.UserId == userId);

            if (userProfile == null)
            {
                return NotFound();
            }

            // Double select 'cause FavouriteMovie has Movie;
            var movies = userProfile.Marks.Select(m => m.Movie).OrderBy(m => m.Name);

            var marks = userProfile.Marks.OrderBy(m => m.Movie.Name);

            var moviesAndMarks = movies.Zip(marks);

            var viewModel = new UserMoviesViewModel
            {
                MoviesAndMarks = moviesAndMarks,

                ForCurrentUser = userId == currentUserId,

                UserName = userProfile.User.UserName,

                ReturnUrl = Url.RouteUrl("Viewed", new { UserId = userId })
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddDeleteFavouriteMovie(int id, string returnUrl)
        {
            var userId = _userManager.GetUserId(User);

            var userProfile = await _context.MoviesProfiles
                    .Include(p => p.FavouriteMovies)
                    .FirstOrDefaultAsync(p => p.UserId == userId);

            var favMovie = await _context.FavouriteMovies.FirstOrDefaultAsync(f => f.MovieId == id);

            string isFavourite;

            //'Cause m2m between fav model and user profile
            if (!userProfile.FavouriteMovies.Any(m => m.MovieId == favMovie.Id))
            {
                userProfile.FavouriteMovies.Add(new UserFavourites { MovieId = favMovie.Id, ProfileId = userProfile.Id });

                isFavourite = _localizer["In Favourites"];

                _logger.LogInformation("User `{0}` has added Movie {1} or fav {2} to his favourites", userId, id, favMovie.Id);
            }
            else
            {
                var userFavMovie = userProfile.FavouriteMovies.FirstOrDefault(m => m.MovieId == favMovie.Id);
                userProfile.FavouriteMovies.Remove(userFavMovie);
                isFavourite = _localizer["Add Favourite"];
                _logger.LogInformation("User `{0}` has removed Movie {1} or fav {2} from his favourites", userId, id, favMovie.Id);
            }

            await _context.SaveChangesAsync();

            return Json( new { isFavourite });

        }
    }
}

MovieSearch/MovieSearch/Views/Movies/Create.cshtml
@model MovieSearch.ViewModels.Movies.MovieEditViewModel
@inject IViewLocalizer Localizer

@{
    ViewData["Title"] = Localizer["Create"];
}

<h1>@ViewData["Title"]</h1>

<h4>@Localizer["Movie"]</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Movie.Name" class="control-label"></label>
                <input asp-for="Movie.Name" class="form-control" />
                <span asp-validation-for="Movie.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Movie.Image" class="control-label"></label>
                <input asp-for="Movie.Image" class="form-control" />
                <span asp-validation-for="Movie.Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Movie.Title" class="control-label"></label>
                <textarea asp-for="Movie.Title" class="form-control"> </textarea>
                <span asp-validation-for="Movie.Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Movie.Year" class="control-label"></label>
                <input asp-for="Movie.Year" class="form-control" />
                <span asp-validation-for="Movie.Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Movie.Country" class="control-label"></label>
                <input asp-for="Movie.Country" class="form-control" />
                <span asp-validation-for="Movie.Country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label for="GenreId" class="control-label">Genre</label>
                <select asp-for="Movie.GenreId" class="form-control" asp-items="Model.Genres"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">@Localizer["Back"]</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MovieSearch/MovieSearch/Views/Movies/Delete.cshtml
@model MovieSearch.Models.Movie
@inject IViewLocalizer Localizer

@{
    ViewData["Title"] = Localizer["Delete"];
}

<h1>@ViewData["Title"]</h1>

<h3>@Localizer["Sure"]</h3>
<div>
    <h4>@Localizer["Movie"]</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Localizer["Name"]
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Localizer["Year"]
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Year)
        </dd>
        <dt class = "col-sm-2">
            @Localizer["Country"]
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Country)
        </dd>
        <dt class = "col-sm-2">
            @Localizer["OveralRating"]
        </dt>
        <dd class = "col-sm-10">
            <rating class="rating-details">@Model.OveralRating</rating>
        </dd>
        <dt class = "col-sm-2">
            @Localizer["Genre"]
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genre.Name)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="@Localizer["Delete"]" class="btn btn-danger" />
        <a asp-action="Index" class="btn badge-primary">@Localizer["Back"]</a>
    </form>
</div>

MovieSearch/MovieSearch/Views/Movies/Details.cshtml
@model MovieSearch.ViewModels.Movies.MovieDetailsViewModel
@inject IViewLocalizer Localizer
@{
    ViewData["Title"] = Localizer["Details"];
}
<link rel="stylesheet" href="~/css/reviews.css" />
<h1>@ViewData["Title"]</h1>

<div class="row">

    <div class="col-md-3">
        <img class="img-thumbnail" src="@Model.Movie.Image" alt="@Model.Movie.Name" />
        @if (User.Identity.IsAuthenticated)
        {
            <div class="div-m-b">
                <form asp-action="Vote" asp-controller="Vote" id="form-details-mark">

                    <input type="hidden" asp-for="Mark.Id" />
                    <input type="hidden" id="Mark_MovieId" name="Mark.MovieId" asp-for="Movie.Id" />
                    <input type="hidden" asp-for="Mark.UserProfileId" />
                    <div class="star-rating">
                        <div class="star-rating__wrap">
                            @for (int i = 1; i <= 10; i++)
                            {
                                <input class="star-rating__input" id=@($"star-rating-{i}") type="radio" asp-for="Mark.Value" value=@($"{i}")>
                                <label class="star-rating__ico fa fa-star-o fa-lg" for=@($"star-rating-{i}") title="@i of 10"></label>
                            }
                            <i class="fa fa-times cancel-rating__input"></i>
                        </div>
                    </div>

                </form>
            </div>
            <div class="div-m-b">
                <form asp-action="AddDeleteFavouriteMovie" asp-controller="UserMovies">

                    <input type="hidden" name="Id" value="@Model.Movie.Id" />
                    <button type="button" class="btn btn-primary btn-fav">@Model.IsFavourite</button>


                    @*<input type="submit" value="@Model.IsFavourite" class="btn btn-primary" />*@
                </form>
            </div>
        }
    </div>

    <div class="col-md-9">
        <h4>@Localizer["About"]</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-3">
                @Html.DisplayNameFor(model => model.Movie.Name)
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.Movie.Name)
            </dd>
            <dt class="col-sm-3">
                @Html.DisplayNameFor(model => model.Movie.Year)
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.Movie.Year)
            </dd>
            <dt class="col-sm-3">
                @Html.DisplayNameFor(model => model.Movie.Country)
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.Movie.Country)
            </dd>
            <dt class="col-sm-3">
                @Html.DisplayNameFor(model => model.Movie.Genre)
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.Movie.Genre.Name)
            </dd>
        </dl>
        <hr />
    </div>
</div>
<div class="col-md-7">
    @if (User.Identity.IsAuthenticated && User.IsInRole("SuperAdmin"))
    {
        <div class="div-m-b">
            <p>
                <a asp-action="Edit" asp-route-id="@Model.Movie.Id">@Localizer["Edit"]</a> |
                <a asp-action="Delete" asp-route-id="@Model.Movie.Id">@Localizer["Delete"]</a> |
                <a asp-action="Index">@Localizer["Back"]</a>
            </p>
        </div>
    }

    <div class="div-m-b " style="padding: 0">
        <h4>@Localizer["Description"]</h4>
        <p>@Model.Movie.Title</p>
    </div>

    <div class="div-m-b">
        <span>
            <span style="margin-right:10px; font-size:1.5rem;">@(Localizer["Rating"]):</span>
            <span class="rating-details">@Model.Movie.OveralRating</span>
        </span>
    </div>

    <div class="div-m-b-p">
        <p style="margin-bottom:10px; font-size:1.5rem;">@Localizer["Reviews"]</p>
        <a asp-action="Create" asp-controller="Reviews" asp-route-movieId="@Model.Movie.Id"
           class="btn btn-info" style="margin-bottom: 10px;"><i class="fa fa-comment"></i> @Localizer["Write"]</a>
        @foreach (var review in Model.Reviews)
        {
            <div style="display:flex;">
                <section class="col-md-12">
                    <div class="review_head">
                        <div style="display:flex">
                            <div class="img_avatar">
                                @if (review.UserProfile.User.ProfilePicture != null)
                                {<img class="review_avatar" src="data:image/*;base64,@(Convert.ToBase64String(review.UserProfile.User.ProfilePicture?.Picture))" />
                                }
                                else
                                {
                                    <img class="review_avatar" src="" />
                                }
                            </div>
                            <div class="review_head_info">
                                <a asp-controller="UserMovies" asp-action="Favourites" asp-route-userId="@review.UserProfile.UserId">@review.UserProfile.User.UserName</a>
                                <span style="font-size: 13px;">@review.UserProfile.Reviews.Count @Localizer["Reviews"].Value.ToLower()</span>
                            </div>
                        </div>
                        <div style="display:flex; align-items:flex-end; margin-left: auto;">
                            <span class="date" style="font-size: 13px;">@review.Date.ToString("g")</span>
                        </div>
                    </div>
                    <div class="review_body">
                        <div style="font-size: 16px; line-height: 20px; white-space: pre-line">
                            <span>@review.Content</span>
                        </div>
                    </div>
                </section>

                @if (User.Identity.IsAuthenticated)
                {
                    @if (review.UserProfileId == Model.ProfileId)
                    {
                        <div>
                            <a class="btn btn-success btn-sm rounded-0" style="margin-bottom: 10px;min-width:29px;"
                               asp-action="Edit" asp-controller="Reviews" asp-route-id="@review.Id">
                                <i class="fa fa-edit"></i>
                            </a>

                            <a class="btn btn-danger btn-sm rounded-0" style="min-width:29px"
                               asp-action="Delete" asp-controller="Reviews" asp-route-id="@review.Id">
                                <i class="fa fa-trash"></i>
                            </a>
                        </div>
                    }

                    else if (User.IsInRole("SuperAdmin") || User.IsInRole("Moderator"))
                    {

                        <div>
                            <a class="btn btn-danger btn-sm rounded-0" style="min-width:29px"
                               asp-action="Delete" asp-controller="Reviews" asp-route-id="@review.Id">
                                <i class="fa fa-trash"></i>
                            </a>
                        </div>

                    }
                }
            </div>
        }

    </div>
</div>

MovieSearch/MovieSearch/Views/Movies/Edit.cshtml
@model MovieSearch.ViewModels.Movies.MovieEditViewModel

@{
    ViewData["Title"] = Localizer["Edit"];
}

<h1>@ViewData["Title"]</h1>

<h4>@Localizer["Movie"]</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Movie.Id" />
            <input type="hidden" asp-for="Movie.OveralRating" />
            <div class="form-group">
                <label asp-for="Movie.Name" class="control-label"></label>
                <input asp-for="Movie.Name" class="form-control" />
                <span asp-validation-for="Movie.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Movie.Image" class="control-label"></label>
                <input asp-for="Movie.Image" class="form-control" />
                <span asp-validation-for="Movie.Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Movie.Title" class="control-label"></label>
                <textarea asp-for="Movie.Title" class="form-control"></textarea>
                <span asp-validation-for="Movie.Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Movie.Year" class="control-label"></label>
                <input asp-for="Movie.Year" class="form-control" />
                <span asp-validation-for="Movie.Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Movie.Country" class="control-label"></label>
                <input asp-for="Movie.Country" class="form-control" />
                <span asp-validation-for="Movie.Country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label for="GenreId" class="control-label">Genre</label>
                <select asp-for="Movie.GenreId" class="form-control" asp-items="Model.Genres"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">@Localizer["Back"]</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MovieSearch/MovieSearch/Views/Movies/Index.cshtml
@model MovieSearch.ViewModels.Movies.MovieIndexViewModel
@inject IViewLocalizer Localizer


@{
    ViewData["Title"] = Localizer["Index"];
}
<link rel="stylesheet" href="~/css/dropdown.css" />


<div id="view-all">
     @await Html.PartialAsync("_ViewAll", Model)   
</div>