MovieSearch/MovieSearch/ViewModels/NavigationListViewComponent.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MovieSearch.Models;
using MovieSearch.ViewModels.UserMovies;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieSearch.ViewModels
{
    public class NavigationListViewComponent : ViewComponent
    {
        private readonly UserManager<ApplicationUser> _userManager;

        public NavigationListViewComponent(UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
        }

        public IViewComponentResult Invoke(object activePage)
        {
            HttpContext.Request.RouteValues.TryGetValue("userId", out var userId);

            var viewModel = new UserMoviesNavigationViewModel
            {             
                UserId = userId.ToString(),

                ActivePage = activePage.ToString()
            };

            return View(viewModel);
        }
    }

}

MovieSearch/MovieSearch/ViewModels/UserMovies/UserMoviesNavigationViewModel.cs
namespace MovieSearch.ViewModels.UserMovies
{
    public class UserMoviesNavigationViewModel
    {
        public string Index => "Favourites";

        public string ViewedMovies => "ViewedMovies";

        public string UserId { get; set; }

        public string ActivePage { get; set; }
    }
}

MovieSearch/MovieSearch/ViewModels/UserMovies/UserMoviesViewModel.cs
using MovieSearch.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieSearch.ViewModels.UserMovies
{
    public class UserMoviesViewModel
    {
        public bool ForCurrentUser { get; set; }
      
        public string ReturnUrl { get; set; }

        public string UserName { get; set; }
        
        public IEnumerable<(Movie Movie, MovieMark Mark)> MoviesAndMarks { get; set; }
    }
}

MovieSearch/MovieSearch/Controllers/UserMoviesController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion.Internal;
using Microsoft.Extensions.Localization;
using Microsoft.Extensions.Logging;
using MovieSearch.Data;
using MovieSearch.Models;
using MovieSearch.ViewModels.UserMovies;

namespace MovieSearch.Controllers
{
    [Authorize]
    public class UserMoviesController : Controller
    {

        public class MovieComparer : IEqualityComparer<Movie>
        {
            public bool Equals([AllowNull] Movie x, [AllowNull] Movie y)
            {
                if (y == null || x == null)
                {
                    return false;
                }

                // TODO: write your implementation of Equals() here
                return x.Id == y.Id;
            }

            public int GetHashCode([DisallowNull] Movie obj)
            {
                return base.GetHashCode();
            }
        }

        private readonly ApplicationDbContext _context;
        private readonly IStringLocalizer<UserMoviesController> _localizer;
        private readonly ILogger<UserMoviesController> _logger;
        private readonly UserManager<ApplicationUser> _userManager;

        public UserMoviesController(
            ILogger<UserMoviesController> logger,
            ApplicationDbContext context,
            UserManager<ApplicationUser> userManager,
            IStringLocalizer<UserMoviesController> localizer)
        {
            _logger = logger;
            _context = context;
            _localizer = localizer;
            _userManager = userManager;
        }

        [Route("ViewedMovies/{userId:Guid}/[Action]", Name = "Favourites")]
        public async Task<IActionResult> Favourites(string userId)
        {
            var currentUserId = _userManager.GetUserId(User);

            var userProfile = await _context.MoviesProfiles
                .Include(u => u.User)
                .Include(p => p.FavouriteMovies)
                .ThenInclude(f => f.Movie)
                .ThenInclude(f => f.Movie)
                .ThenInclude(m => m.Genre)
                .Include(p => p.Marks)
                .ThenInclude(m => m.Movie)
                .FirstOrDefaultAsync(p => p.UserId == userId);

            if(userProfile == null)
            {
                return NotFound();
            }

            // Double select 'cause FavouriteMovie has Movie;
            var favourites = userProfile.FavouriteMovies
                .Select(f => f.Movie)
                .Select(f => f.Movie)
                .OrderBy(f => f.Name);

            var marks = userProfile.Marks.OrderBy(m => m.Movie.Name);

            var favouritesMarks = marks
                .Where((m) => { return favourites.Any(mv => mv.Id == m.MovieId); })
                .OrderBy(m => m.Movie.Name);

            var markedFavourites = favouritesMarks.Select(m => m.Movie);

            var unmarkedFavourites = favourites.Except(markedFavourites, new MovieComparer());

            var moviesAndMarks = markedFavourites.Zip(favouritesMarks).ToList();

            foreach (var movie in unmarkedFavourites)
            {
                moviesAndMarks.Add((movie, null));
            }

            moviesAndMarks = moviesAndMarks.OrderBy(m => m.First.Name).ToList();

            var viewModel = new UserMoviesViewModel
            {
                MoviesAndMarks = moviesAndMarks,

                ForCurrentUser = userId == currentUserId,

                UserName = userProfile.User.UserName,

                ReturnUrl = Url.RouteUrl("Favourites", new { UserId = userId }) //"/UserMovies/"
            };

            return View(viewModel);
        }

        [Route("ViewedMovies/{userId:Guid}/[Action]", Name = "Viewed")]
        public async Task<IActionResult> ViewedMovies(string userId)
        {
            var currentUserId = _userManager.GetUserId(User);
            var userProfile = await _context.MoviesProfiles
                .Include(p => p.User)
                .Include(p => p.Marks)
                .ThenInclude(m => m.Movie)
                .FirstOrDefaultAsync(p => p.UserId == userId);

            if (userProfile == null)
            {
                return NotFound();
            }

            // Double select 'cause FavouriteMovie has Movie;
            var movies = userProfile.Marks.Select(m => m.Movie).OrderBy(m => m.Name);

            var marks = userProfile.Marks.OrderBy(m => m.Movie.Name);

            var moviesAndMarks = movies.Zip(marks);

            var viewModel = new UserMoviesViewModel
            {
                MoviesAndMarks = moviesAndMarks,

                ForCurrentUser = userId == currentUserId,

                UserName = userProfile.User.UserName,

                ReturnUrl = Url.RouteUrl("Viewed", new { UserId = userId })
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddDeleteFavouriteMovie(int id, string returnUrl)
        {
            var userId = _userManager.GetUserId(User);

            var userProfile = await _context.MoviesProfiles
                    .Include(p => p.FavouriteMovies)
                    .FirstOrDefaultAsync(p => p.UserId == userId);

            var favMovie = await _context.FavouriteMovies.FirstOrDefaultAsync(f => f.MovieId == id);

            string isFavourite;

            //'Cause m2m between fav model and user profile
            if (!userProfile.FavouriteMovies.Any(m => m.MovieId == favMovie.Id))
            {
                userProfile.FavouriteMovies.Add(new UserFavourites { MovieId = favMovie.Id, ProfileId = userProfile.Id });

                isFavourite = _localizer["In Favourites"];

                _logger.LogInformation("User `{0}` has added Movie {1} or fav {2} to his favourites", userId, id, favMovie.Id);
            }
            else
            {
                var userFavMovie = userProfile.FavouriteMovies.FirstOrDefault(m => m.MovieId == favMovie.Id);
                userProfile.FavouriteMovies.Remove(userFavMovie);
                isFavourite = _localizer["Add Favourite"];
                _logger.LogInformation("User `{0}` has removed Movie {1} or fav {2} from his favourites", userId, id, favMovie.Id);
            }

            await _context.SaveChangesAsync();

            return Json( new { isFavourite });

        }
    }
}

MovieSearch/MovieSearch/Views/UserMovies/Favourites.cshtml
@model MovieSearch.ViewModels.UserMovies.UserMoviesViewModel
@inject IViewLocalizer Localizer;

@{
    ViewData["Title"] = Localizer["Favourites"];
    ViewData["ActivePage"] = "Favourites";
}

<h4 style="margin-bottom:10px;">@ViewData["Title"]</h4>

<table class="table table-sm table-striped">
    <thead class="thead-dark">
        <tr>
            <th>
                @Localizer["Movie"]
            </th>
            @if (Model.ForCurrentUser)
            {
                <th>
                    @Localizer["MyMark"]
                </th>
            }
            else
            {
                <th>
                    @Localizer["Mark"]
                </th>
            }
            <th>
                @Localizer["Rating"]
            </th>

            <th>
            </th>

        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model.MoviesAndMarks)
        {
            <tr>
                <td>
                    @Html.ActionLink(item.Movie.Name + $"({item.Movie.Year})",
                   "Details",
                   "Movies",
                   new { id = item.Movie.Id })
                </td>

                <td>
                    <rating class="rating-details">@item.Mark?.Value</rating>
                </td>

                <td>
                    <rating class="rating-details">@item.Movie.OveralRating</rating>
                </td>
                @if (Model.ForCurrentUser)
                {
                    <td>
                        <form asp-action="AddDeleteFavouriteMovie">

                            <input type="hidden" name="id" value="@item.Movie.Id" />
                            <input type="hidden" asp-for="ReturnUrl" />
                            <button type="button" data-fav="Delete" class="btn btn-info btn-fav">@Localizer["Delete"]</button>
                            @*<input type="submit" value="Delete" class="btn btn-info" />*@
                        </form>
                    </td>
                }
                else
                {
                    <td>
                        <a class="btn btn-info" title="@item.Movie.Name" asp-action="Details" asp-controller="Movies" asp-route-id="@item.Movie.Id">@Localizer["Add"]</a>
                    </td>
                }
            </tr>
        }
    </tbody>
</table>

MovieSearch/MovieSearch/Views/UserMovies/ViewedMovies.cshtml
@model MovieSearch.ViewModels.UserMovies.UserMoviesViewModel
@inject IViewLocalizer Localizer

@{
    ViewData["Title"] = Localizer["ViewedMovies"];
    ViewData["ActivePage"] = "ViewedMovies";
}

@if (Model.ForCurrentUser)
{
    <h4 style="margin-bottom:10px;">
        @ViewData["Title"]

    </h4>
}
else
{
    <h4 style="margin-bottom:10px;">
        @($"{Model.UserName}'s {ViewBag.Title.Value.ToLower()}")
    </h4>
}


<table class="table table-sm table-striped">
    <thead class="thead-dark">
        <tr>
            <th>
                @Localizer["Movie"]
            </th>
            @if (Model.ForCurrentUser)
            {
                <th>
                    @Localizer["MyMark"]
                </th>
            }
            else
            {
                <th>
                    @($"{Model.UserName}'s") @Localizer["Mark"].Value.ToLower() 
                </th>
            }
            <th>
                @Localizer["Rating"]
            </th>
            <th>
            </th>

        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model.MoviesAndMarks)
        {
            <tr>
                <td>
                    @Html.ActionLink(item.Movie.Name + $"({item.Movie.Year})",
                   "Details",
                   "Movies",
                   new { id = item.Movie.Id })
                </td>
                <td>
                    <rating class="rating-details">@item.Mark.Value</rating>
                </td>
                <td>
                    <rating class="rating-details">@item.Movie.OveralRating</rating>
                </td>
                @*@if (Model.ForCurrentUser)
                    {
                        <td>
                            <form asp-action="Vote" asp-controller="Vote">

                                <input type="hidden" asp-for="ReturnUrl" />
                                <input type="hidden" id="Mark_Id" name="Id" value="@item.Mark.Id" />
                                <input type="hidden" id="Mark_MovieId" name="MovieId" value="@item.Movie.Id" />
                                <input type="hidden" id="Mark_UserProfileId" name="UserProfileId" value="@item.Mark.UserProfileId" />
                                <div class="dropdown">
                                    <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" id="ddBtn">
                                        Give a mark
                                    </button>
                                    <div class="dropdown-menu" style="min-width:14rem;" aria-labelledby="ddBtn">
                                        <div class="dropdown-item star-rating" style="padding: 0;">
                                            <div class="star-rating__wrap">
                                                @for (int i = 1; i <= 10; i++)
                                                {
                                                    <input class="star-rating__input" id=@($"star-rating-{i}") type="radio" name="Value" asp-for="@item.Mark.Value" value=@($"{i}")>
                                                    <label class="star-rating__ico fa fa-star-o fa-lg" style="margin-bottom:0;" for=@($"star-rating-{i}") title="@i of 10 "></label>
                                                }
                                                <i class="fa fa-times cancel-rating__input"></i>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </form>
                        </td>
                    }
                    else
                    {
                        }*@
                <td>
                    <a class="btn btn-info" title="@item.Movie.Name" asp-action="Details" asp-controller="Movies" asp-route-id="@item.Movie.Id">@Localizer["Rate"]</a>
                </td>

            </tr>
        }
    </tbody>
</table>

MovieSearch/MovieSearch/Views/UserMovies/_Layout.cshtml
@{
    Layout = "/Views/Shared/_Layout.cshtml";
}

@inject IViewLocalizer Localizer

<span id="copyMsg" style="color:green;">@Localizer["Link"]</span>
@if (Model.ForCurrentUser)
{

    <h2>@Localizer["Manage"] <strong id="profileLink" style="color: blue"><u>@Localizer["Your"]</u></strong> @Localizer["Profile"]</h2>
}
else
{
    <h2><strong id="profileLink" style="color: blue"><u>@($"{Model.UserName}'s")</u></strong> @Localizer["Profile"]</h2>
}

<div>
    @if (Model.ForCurrentUser)
    {

        <h4>@Localizer["Browse"] @Localizer["Your2"] @Localizer["Favourite movies"]</h4>
    }
    else
    {
        <h4>@Localizer["Browse"] @($"{Model.UserName}'s") @Localizer["Favourite movies"]</h4>
    }
    <hr />
    <div class="row">
        <div class="col-md-3">
            @await Component.InvokeAsync("NavigationList", ViewData["ActivePage"])
        </div>
        <div class="col-md-9">
            @RenderBody()
        </div>
    </div>
</div>

@section Scripts {
    @RenderSection("Scripts", required: false)
    <script type="text/javascript">
        $(function () {
            $('#copyMsg').hide();

            $('#profileLink').click(function () {
                console.log('profileLink clicked');
                console.log(window.location.href);

                navigator.clipboard.writeText(window.location.href)
                    .then(() => {
                        $('#copyMsg').fadeToggle(300).delay(300).fadeToggle(500);

                    })
                    .catch(err => {
                        console.log(err);
                    });
            });
        });
    </script>
}